'use client';

import { useState, useEffect, useRef } from 'react';
import { getMonthlyAttendanceRegister } from '@/app/_lib/actions/attendance';
import { getFullProfile } from '@/app/_lib/actions/profile';
import { Button } from '@/app/_components/ui/button';
import { Card } from '@/app/_components/ui/card';
import { PageSpinner } from '@/app/_components/ui/spinner';
import { Download, Calendar as CalendarIcon, Printer, Search, AlertCircle } from 'lucide-react';

export default function MonthlyAttendanceRegisterPage() {
  const [data, setData] = useState<any>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [teacherProfile, setTeacherProfile] = useState<any>(null);
  const [month, setMonth] = useState(new Date().getMonth() + 1);
  const [year, setYear] = useState(new Date().getFullYear());
  const printRef = useRef<HTMLDivElement>(null);

  const loadData = async () => {
    setIsLoading(true);
    const { data: profile } = await getFullProfile();
    setTeacherProfile(profile);

    if (profile?.teacher?.class_id) {
      const result = await getMonthlyAttendanceRegister(profile.teacher.class_id, year, month);
      setData(result.data);
    }
    setIsLoading(false);
  };

  useEffect(() => {
    loadData();
  }, [month, year]);

  const handlePrint = () => {
    window.print();
  };

  const getDayLabel = (d: number) => {
    if (!data) return '';
    const date = new Date(year, month - 1, d);
    const days = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
    return days[date.getDay()];
  };

  if (isLoading) return <PageSpinner />;

  if (!teacherProfile?.teacher?.class_id) {
    return (
      <div className="py-24 text-center glass-card bg-bg-secondary/30 rounded-3xl">
         <AlertCircle className="h-16 w-16 text-amber-500/50 mx-auto mb-6" />
         <p className="text-text-secondary font-black text-xl tracking-tight">No class assigned. Please contact admin.</p>
      </div>
    );
  }

  const daysArray = Array.from({ length: data?.daysInMonth || 31 }, (_, i) => i + 1);

  return (
    <div className="space-y-8 pb-20 print:space-y-0 print:pb-0">
      <div className="flex flex-col lg:flex-row justify-between items-start lg:items-end gap-6 print:hidden">
        <div>
          <h1 className="text-4xl font-black text-text-primary tracking-tighter">Monthly Register</h1>
          <p className="text-text-secondary font-medium">Class: {teacherProfile.teacher.classes?.name}</p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <select 
            value={month} 
            onChange={(e) => setMonth(parseInt(e.target.value))}
            className="px-4 py-2 bg-white border border-border rounded-xl text-sm font-black outline-none"
          >
            {Array.from({ length: 12 }).map((_, i) => (
              <option key={i+1} value={i+1}>{new Date(2000, i, 1).toLocaleString('default', { month: 'long' })}</option>
            ))}
          </select>
          <select 
            value={year} 
            onChange={(e) => setYear(parseInt(e.target.value))}
            className="px-4 py-2 bg-white border border-border rounded-xl text-sm font-black outline-none"
          >
            {[year-1, year, year+1].map(y => (
              <option key={y} value={y}>{y}</option>
            ))}
          </select>

          <Button onClick={handlePrint} variant="outline" className="bg-white" leftIcon={<Printer className="h-4 w-4"/>}>
            Print / PDF
          </Button>
        </div>
      </div>

      <div className="bg-white rounded-xl shadow-2xl overflow-hidden print:shadow-none print:bg-transparent" ref={printRef}>
        {/* Print Header */}
        <div className="hidden print:block p-8 text-center border-b border-black">
          <h1 className="text-2xl font-black uppercase mb-1">Monthly Attendance Register</h1>
          <h2 className="text-lg font-bold">Class: {teacherProfile.teacher.classes?.name} | Month: {new Date(year, month - 1, 1).toLocaleString('default', { month: 'long' })} {year}</h2>
          <p className="text-sm mt-2">Generated by: {teacherProfile.full_name}</p>
        </div>

        <div className="overflow-x-auto w-full pb-4">
          <table className="w-full text-[10px] text-center border-collapse print:text-[8px]">
            <thead className="bg-bg-tertiary/50 uppercase tracking-tighter font-black text-text-tertiary print:bg-gray-100 print:text-black">
              <tr>
                <th className="px-4 py-3 text-left sticky left-0 z-20 bg-white border-b border-r border-border print:border-black">Roll No</th>
                <th className="px-4 py-3 text-left sticky left-[80px] z-20 bg-white border-b border-r border-border min-w-[150px] print:border-black">Student Name</th>
                {daysArray.map(d => (
                  <th key={d} className="px-1.5 py-3 border-b border-r border-border min-w-[28px] print:border-black">
                    <div className="flex flex-col items-center">
                      <span className="text-[8px] opacity-60 print:opacity-100">{getDayLabel(d)}</span>
                      <span>{d}</span>
                    </div>
                  </th>
                ))}
                <th className="px-2 py-3 border-b border-r border-border bg-emerald-50 text-emerald-700 print:border-black">P</th>
                <th className="px-2 py-3 border-b border-r border-border bg-red-50 text-red-700 print:border-black">A</th>
                <th className="px-2 py-3 border-b border-r border-border bg-amber-50 text-amber-700 print:border-black">L</th>
                <th className="px-2 py-3 border-b border-border bg-blue-50 text-blue-700 print:border-black">%</th>
              </tr>
            </thead>
            <tbody className="print:text-black">
              {data?.students.map((student: any, idx: number) => (
                <tr key={student.userId} className={idx % 2 === 0 ? "bg-white" : "bg-bg-secondary/10"}>
                  <td className="px-4 py-2 text-left sticky left-0 z-10 bg-inherit border-b border-r border-border font-bold print:border-black">{student.rollNumber || '-'}</td>
                  <td className="px-4 py-2 text-left sticky left-[80px] z-10 bg-inherit border-b border-r border-border font-bold truncate max-w-[150px] print:border-black">{student.name}</td>
                  {daysArray.map(d => {
                    const status = student.days[d];
                    let bgColor = '';
                    let textColor = 'text-text-primary print:text-black';
                    if (status === 'P' || status === 'Late') { bgColor = 'bg-emerald-50 print:bg-transparent'; textColor = 'text-emerald-600 font-black print:text-black'; }
                    else if (status === 'A') { bgColor = 'bg-red-50 print:bg-transparent'; textColor = 'text-red-600 font-black print:text-black'; }
                    else if (status === 'L') { bgColor = 'bg-amber-50 print:bg-transparent'; textColor = 'text-amber-600 font-black print:text-black'; }
                    else if (status === 'H' || status === 'OD') { bgColor = 'bg-blue-50/50 print:bg-transparent'; textColor = 'text-blue-500 font-black text-[8px] print:text-black'; }
                    
                    return (
                      <td key={d} className={`px-1 py-2 border-b border-r border-border ${bgColor} print:border-black`}>
                        <span className={textColor}>{status || '-'}</span>
                      </td>
                    );
                  })}
                  <td className="px-2 py-2 border-b border-r border-border font-black text-emerald-600 print:border-black print:text-black bg-emerald-50/30">{student.stats.present}</td>
                  <td className="px-2 py-2 border-b border-r border-border font-black text-red-600 print:border-black print:text-black bg-red-50/30">{student.stats.absent}</td>
                  <td className="px-2 py-2 border-b border-r border-border font-black text-amber-600 print:border-black print:text-black bg-amber-50/30">{student.stats.leave}</td>
                  <td className="px-2 py-2 border-b border-border font-black text-blue-600 print:border-black print:text-black bg-blue-50/30">{student.stats.percentage}%</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        <div className="p-4 border-t border-border flex flex-wrap gap-4 text-[10px] font-black uppercase tracking-widest text-text-tertiary bg-bg-tertiary/50 print:bg-white print:border-black print:text-black">
           <span className="flex items-center gap-1"><span className="w-3 h-3 bg-emerald-100 rounded inline-block print:border print:border-black" /> P = Present</span>
           <span className="flex items-center gap-1"><span className="w-3 h-3 bg-red-100 rounded inline-block print:border print:border-black" /> A = Absent</span>
           <span className="flex items-center gap-1"><span className="w-3 h-3 bg-amber-100 rounded inline-block print:border print:border-black" /> L = Leave</span>
           <span className="flex items-center gap-1"><span className="w-3 h-3 bg-emerald-50 rounded inline-block print:border print:border-black" /> Late = Late</span>
           <span className="flex items-center gap-1"><span className="w-3 h-3 bg-blue-50 rounded inline-block print:border print:border-black" /> H = Holiday</span>
           <span className="flex items-center gap-1"><span className="w-3 h-3 bg-blue-50 rounded inline-block print:border print:border-black" /> OD = Off Day</span>
        </div>
      </div>
      
      {/* Print styles */}
      <style dangerouslySetInnerHTML={{__html: `
        @media print {
          body * {
            visibility: hidden;
          }
          #print-area, #print-area * {
            visibility: visible;
          }
          #print-area {
            position: absolute;
            left: 0;
            top: 0;
            width: 100%;
          }
        }
      `}} />
    </div>
  );
}
